name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    env:
      frontend-dir: ./frontend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ${{ env.frontend-dir }}
        run: npm ci
      - name: Build (typecheck) the project
        working-directory: ${{ env.frontend-dir }}
        run: npm run build
      - name: Lint the project
        working-directory: ${{ env.frontend-dir }}
        run: npm run lint

  image:
    needs: build
    uses: ./.github/workflows/image.yml
    secrets: inherit

  deploy:
    permissions:
      contents: write
    needs: image
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
